version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: banco_treino_nestjs
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: nest_db
      MYSQL_USER: caio_user
      MYSQL_PASSWORD: caio_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
